/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIGAMARKS2.Experience;

import mx.unam.patronato.auditoria.siga.core.model.Documento;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author José de Jesús Herrera Ledón
 */
public class jPanelRecentFilesList extends javax.swing.JPanel {

    private List<String> filesNames = new ArrayList();//nombres de los archivos recientes
    private String loggin ="jesus";

    /**
     * Creates new form jPanelRecentFilesList
     */

    public jPanelRecentFilesList() {
        initComponents();
        getFileNamesFromObjectsFiles(loggin);
    }

    public void getFileNamesFromObjectsFiles(String loggin) {
        filesNames = UserExperienceListRecentDocsImpl.readFileUserExpirenceObj(loggin).getNameOfFiles();
        int lngFilesNames =  filesNames.size();
        if (filesNames != null) {
            jButtonFile1.setText(filesNames.get(lngFilesNames));
            if((lngFilesNames--) > 0){ 
                jButtonFile2.setText(filesNames.get(lngFilesNames));
            }else{
                return;
            }
            if(lngFilesNames-- > 0){
                jButtonFile3.setText(filesNames.get(lngFilesNames));
            }else{
                return;
            }
            /*
            jButtonFile4.setText(filesNames.get(4));
            jButtonFile5.setText(filesNames.get(5));
            jButtonFile6.setText(filesNames.get(6));
            jButtonFile7.setText(filesNames.get(7));
            jButtonFile8.setText(filesNames.get(8));
            jButtonFile9.setText(filesNames.get(9));
            jButtonFile10.setText(filesNames.get(10));
        */
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDocumentosRecientes = new javax.swing.JLabel();
        jButtonFile2 = new javax.swing.JButton();
        jButtonFile1 = new javax.swing.JButton();
        jButtonFile4 = new javax.swing.JButton();
        jButtonFile5 = new javax.swing.JButton();
        jButtonFile6 = new javax.swing.JButton();
        jButtonFile3 = new javax.swing.JButton();
        jButtonFile7 = new javax.swing.JButton();
        jButtonFile8 = new javax.swing.JButton();
        jButtonFile9 = new javax.swing.JButton();
        jButtonFile10 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(330, 640));
        setMinimumSize(new java.awt.Dimension(330, 640));
        setPreferredSize(new java.awt.Dimension(330, 640));

        jLabelDocumentosRecientes.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDocumentosRecientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDocumentosRecientes.setForeground(new java.awt.Color(0, 102, 255));
        jLabelDocumentosRecientes.setText("Documentos Recientes");

        jButtonFile1.setBackground(new java.awt.Color(0, 204, 255));

        jButtonFile4.setActionCommand("");

        jButtonFile5.setActionCommand("");

        jButtonFile6.setActionCommand("");

        jButtonFile8.setActionCommand("");

        jButtonFile9.setActionCommand("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDocumentosRecientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFile4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFile5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFile10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDocumentosRecientes)
                .addGap(18, 18, 18)
                .addComponent(jButtonFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButtonFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String[] args) {
        jPanelRecentFilesList jp = new jPanelRecentFilesList();
        jp.setVisible(true);
    }

    public List<String> getFilesNames() {
        return filesNames;
    }

    public void setFilesNames(List<String> filesNames) {
        this.filesNames = filesNames;
    }

    public String getLoggin() {
        return loggin;
    }

    public void setLoggin(String loggin) {
        this.loggin = loggin;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFile1;
    private javax.swing.JButton jButtonFile10;
    private javax.swing.JButton jButtonFile2;
    private javax.swing.JButton jButtonFile3;
    private javax.swing.JButton jButtonFile4;
    private javax.swing.JButton jButtonFile5;
    private javax.swing.JButton jButtonFile6;
    private javax.swing.JButton jButtonFile7;
    private javax.swing.JButton jButtonFile8;
    private javax.swing.JButton jButtonFile9;
    private javax.swing.JLabel jLabelDocumentosRecientes;
    // End of variables declaration//GEN-END:variables

}
