/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SIGAMARKS2.FramesAndPanels;

import javax.swing.JFrame;

/**
 *
 * @author José de Jesús Herrera Ledón
 */
public class JPanelWorkMark extends javax.swing.JPanel {
    
    /**
     * Creates new form JPanelWorkMark
     */
    public JPanelWorkMark() {
        initComponents();
    }
    
    public static void main(String[] args) {
        JFrame jf = new JFrame("Prueba de panel");
        jf.setSize(1500, 1000);
        JPanelWorkMark jpwm = new JPanelWorkMark();
        jpwm.setSize(1500, 1000);
        jf.add(jpwm);
        jpwm.setVisible(true);
        jf.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMainMenu = new javax.swing.JPanel();
        jButtonLogo = new javax.swing.JButton();
        jToggleButtonConsultaTrabajos = new javax.swing.JToggleButton();
        jToggleButtontrabajosEnEjecucion = new javax.swing.JToggleButton();
        jToggleButtonConsultaObservaciones = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1800, 1300));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        setLayout(new java.awt.BorderLayout());

        jPanelMainMenu.setBackground(new java.awt.Color(21, 34, 60));
        jPanelMainMenu.setForeground(new java.awt.Color(21, 34, 60));
        jPanelMainMenu.setMaximumSize(new java.awt.Dimension(1800, 68));
        jPanelMainMenu.setMinimumSize(new java.awt.Dimension(1300, 68));
        jPanelMainMenu.setPreferredSize(new java.awt.Dimension(1500, 68));

        jButtonLogo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SIGAMARKS2/logo/unamTc.png"))); // NOI18N
        jButtonLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogo.setMaximumSize(new java.awt.Dimension(65, 70));
        jButtonLogo.setMinimumSize(new java.awt.Dimension(65, 70));
        jButtonLogo.setPreferredSize(new java.awt.Dimension(65, 70));
        jButtonLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonLogo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jToggleButtonConsultaTrabajos.setBackground(new java.awt.Color(21, 34, 60));
        jToggleButtonConsultaTrabajos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButtonConsultaTrabajos.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonConsultaTrabajos.setText("Consulta Trabajos");
        jToggleButtonConsultaTrabajos.setToolTipText("Consultar los trabajos de Auditoria");
        jToggleButtonConsultaTrabajos.setBorder(null);
        jToggleButtonConsultaTrabajos.setBorderPainted(false);
        jToggleButtonConsultaTrabajos.setContentAreaFilled(false);
        jToggleButtonConsultaTrabajos.setFocusPainted(false);

        jToggleButtontrabajosEnEjecucion.setBackground(new java.awt.Color(21, 34, 60));
        jToggleButtontrabajosEnEjecucion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButtontrabajosEnEjecucion.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtontrabajosEnEjecucion.setText("Trabajos en ejecución y por Iniciar");
        jToggleButtontrabajosEnEjecucion.setBorder(null);
        jToggleButtontrabajosEnEjecucion.setBorderPainted(false);
        jToggleButtontrabajosEnEjecucion.setContentAreaFilled(false);
        jToggleButtontrabajosEnEjecucion.setFocusPainted(false);

        jToggleButtonConsultaObservaciones.setBackground(new java.awt.Color(21, 34, 60));
        jToggleButtonConsultaObservaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButtonConsultaObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonConsultaObservaciones.setText("Consultar Informes y observaciones");
        jToggleButtonConsultaObservaciones.setBorder(null);
        jToggleButtonConsultaObservaciones.setBorderPainted(false);
        jToggleButtonConsultaObservaciones.setContentAreaFilled(false);
        jToggleButtonConsultaObservaciones.setFocusPainted(false);

        javax.swing.GroupLayout jPanelMainMenuLayout = new javax.swing.GroupLayout(jPanelMainMenu);
        jPanelMainMenu.setLayout(jPanelMainMenuLayout);
        jPanelMainMenuLayout.setHorizontalGroup(
            jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainMenuLayout.createSequentialGroup()
                .addComponent(jButtonLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonConsultaTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtontrabajosEnEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonConsultaObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 699, Short.MAX_VALUE))
        );
        jPanelMainMenuLayout.setVerticalGroup(
            jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonConsultaTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtontrabajosEnEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonConsultaObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanelMainMenu, java.awt.BorderLayout.NORTH);
        jPanelMainMenu.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMainMenu;
    private javax.swing.JToggleButton jToggleButtonConsultaObservaciones;
    private javax.swing.JToggleButton jToggleButtonConsultaTrabajos;
    private javax.swing.JToggleButton jToggleButtontrabajosEnEjecucion;
    // End of variables declaration//GEN-END:variables
}
