/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SIGAMARKS2.FramesAndPanels;

import javax.swing.JFrame;

/**
 *
 * @author José de Jesús Herrera Ledón
 */
public class PDFPagesEditor extends javax.swing.JPanel {

    /**
     * Creates new form PDFPagesEditor
     */
    public PDFPagesEditor() {
        initComponents();
    }
    public static void main(String[] args) {
        JFrame jf =  new JFrame();
        jf.setSize(1400,1000);
        PDFPagesEditor pdf =  new PDFPagesEditor();
        pdf.setSize(1200, 800);
        jf.add(pdf);
        jf.setVisible(true);
        pdf.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarPDFEditor = new javax.swing.JToolBar();
        jPanelPDFEditor = new javax.swing.JPanel();
        jPanelTree = new javax.swing.JPanel();
        jPanelOriginalPDF = new javax.swing.JPanel();
        jPanelPAgesToADD = new javax.swing.JPanel();
        jLabelTitleOriginalPDF = new javax.swing.JLabel();
        jLabelToAddPDF = new javax.swing.JLabel();
        jButtonQuitar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1400, 1000));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jToolBarPDFEditor.setBackground(new java.awt.Color(21, 34, 60));
        jToolBarPDFEditor.setForeground(new java.awt.Color(255, 168, 37));
        jToolBarPDFEditor.setRollover(true);
        jToolBarPDFEditor.setMaximumSize(new java.awt.Dimension(1400, 40));
        jToolBarPDFEditor.setMinimumSize(new java.awt.Dimension(1200, 40));
        jToolBarPDFEditor.setPreferredSize(new java.awt.Dimension(1200, 40));

        jPanelPDFEditor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPDFEditor.setMaximumSize(new java.awt.Dimension(1400, 1150));
        jPanelPDFEditor.setMinimumSize(new java.awt.Dimension(1200, 950));
        jPanelPDFEditor.setPreferredSize(new java.awt.Dimension(1200, 950));

        jPanelTree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(21, 34, 60), new java.awt.Color(51, 102, 255), null, null));
        jPanelTree.setMaximumSize(new java.awt.Dimension(450, 800));
        jPanelTree.setMinimumSize(new java.awt.Dimension(350, 700));
        jPanelTree.setPreferredSize(new java.awt.Dimension(350, 700));

        javax.swing.GroupLayout jPanelTreeLayout = new javax.swing.GroupLayout(jPanelTree);
        jPanelTree.setLayout(jPanelTreeLayout);
        jPanelTreeLayout.setHorizontalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanelTreeLayout.setVerticalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );

        jPanelOriginalPDF.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOriginalPDF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 34, 60), 3));
        jPanelOriginalPDF.setMaximumSize(new java.awt.Dimension(830, 250));
        jPanelOriginalPDF.setMinimumSize(new java.awt.Dimension(830, 250));
        jPanelOriginalPDF.setPreferredSize(new java.awt.Dimension(830, 250));

        javax.swing.GroupLayout jPanelOriginalPDFLayout = new javax.swing.GroupLayout(jPanelOriginalPDF);
        jPanelOriginalPDF.setLayout(jPanelOriginalPDFLayout);
        jPanelOriginalPDFLayout.setHorizontalGroup(
            jPanelOriginalPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanelOriginalPDFLayout.setVerticalGroup(
            jPanelOriginalPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jPanelPAgesToADD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPAgesToADD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 168, 37), 3));
        jPanelPAgesToADD.setMaximumSize(new java.awt.Dimension(830, 250));
        jPanelPAgesToADD.setMinimumSize(new java.awt.Dimension(830, 250));
        jPanelPAgesToADD.setPreferredSize(new java.awt.Dimension(830, 250));

        javax.swing.GroupLayout jPanelPAgesToADDLayout = new javax.swing.GroupLayout(jPanelPAgesToADD);
        jPanelPAgesToADD.setLayout(jPanelPAgesToADDLayout);
        jPanelPAgesToADDLayout.setHorizontalGroup(
            jPanelPAgesToADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanelPAgesToADDLayout.setVerticalGroup(
            jPanelPAgesToADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jLabelTitleOriginalPDF.setText("Title");

        jLabelToAddPDF.setText(".");

        jButtonQuitar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SIGAMARKS2/ImagenesApp/tache.png"))); // NOI18N
        jButtonQuitar.setText("Quitar ");
        jButtonQuitar.setContentAreaFilled(false);

        jButtonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SIGAMARKS2/ImagenesApp/FlechaRoja.png"))); // NOI18N
        jButtonAgregar.setToolTipText("Agregar");

        javax.swing.GroupLayout jPanelPDFEditorLayout = new javax.swing.GroupLayout(jPanelPDFEditor);
        jPanelPDFEditor.setLayout(jPanelPDFEditorLayout);
        jPanelPDFEditorLayout.setHorizontalGroup(
            jPanelPDFEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPDFEditorLayout.createSequentialGroup()
                .addComponent(jPanelTree, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelPDFEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPDFEditorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPDFEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelPAgesToADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelOriginalPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitleOriginalPDF)
                            .addGroup(jPanelPDFEditorLayout.createSequentialGroup()
                                .addComponent(jLabelToAddPDF)
                                .addGap(366, 366, 366)
                                .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelPDFEditorLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jButtonQuitar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPDFEditorLayout.setVerticalGroup(
            jPanelPDFEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPDFEditorLayout.createSequentialGroup()
                .addGroup(jPanelPDFEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPDFEditorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitleOriginalPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelOriginalPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanelPDFEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelToAddPDF))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPAgesToADD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarPDFEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPDFEditor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBarPDFEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPDFEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JLabel jLabelTitleOriginalPDF;
    private javax.swing.JLabel jLabelToAddPDF;
    private javax.swing.JPanel jPanelOriginalPDF;
    private javax.swing.JPanel jPanelPAgesToADD;
    private javax.swing.JPanel jPanelPDFEditor;
    private javax.swing.JPanel jPanelTree;
    private javax.swing.JToolBar jToolBarPDFEditor;
    // End of variables declaration//GEN-END:variables
}
